---
# description: RedHat specific installation

- name: "Add yum repository | RedHat"
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
    state: absent

- name: "Install telegraf package | RedHat"
  yum:
    name: "telegraf"
    state: absent
  notify: "Restart Telegraf"

